# docker-compose.yml
version: '3.8'

services:
  r1ms:
    build: .
    image: r1ms:latest
    container_name: r1ms
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - RUST_LOG=info
      - HEARTBEAT_PERIOD_SECS=60
      - HEARTBEAT_BURST_LIMIT=100
      - SERVER_LIST_PERIOD_SECS=5
      - SERVER_LIST_BURST_LIMIT=1
      - SERVER_DELETE_PERIOD_SECS=5
      - SERVER_DELETE_BURST_LIMIT=1
      - MAX_SERVERS_PER_IP=3
      - SERVER_TIMEOUT_SECS=300
    volumes:
      - /var/log/r1ms:/var/log/r1ms
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Optional resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
